### ISSUE TITLE
additional data from the private zone

### ISSUE THREAD

**Issue by mireille-raad** [egovmd/opencontracting#10]

**Comment by bezunakarmi** [comment]
We have set a placeholder for the additonal data from the private zone on tender's detail pages. Please have a look at : http://moldova-demo.yipl.com.np/tenders/25610
![screen shot 2017-02-02 at 2 16 03 pm](https://cloud.githubusercontent.com/assets/12218329/22542125/566665aa-e952-11e6-8377-c4fd012463c1.png)

**Comment by mireille-raad** [comment]
For reference, what is the list of the fields that were added?

I see award criteria and eligibility, anything else that might not be showing on this tender?
