### ISSUE TITLE
API

### ISSUE THREAD

**Issue by mireille-raad** [egovmd/opencontracting#11]
Collaborative API Development

Access to updated data based on date filter in the API

**Comment by mireille-raad** [comment]
After our phone call on friday we agreed that we need to put some visual snapshot of the interface to see how data was pulled, at what time, the number of records as well as troubleshooting steps, buttons to restart processes, instructions to give to IT when the data stops getting imported etc...

So, I think as next step... if we have a mockup UI, we can give feedback on it as you try to move forward with DAAC.

**Comment by anjesh** [comment]
Further discussion here https://github.com/younginnovations/opencontracting-moldova/issues/22
