### ISSUE TITLE
Links to Wiki Pages

### ISSUE THREAD

**Issue by mireille-raad** [egovmd/opencontracting#14]
Adding icons in different pages with links to wiki for more detailed information about content in each page.

**Comment by bezunakarmi** [comment]
Links has been added to respective pages for tender, contract , agency and goods & services. A small icon right to the heading has been added. Please have a look at it.
![screen shot 2017-02-22 at 2 48 44 pm](https://cloud.githubusercontent.com/assets/12218329/23204562/2f89a2d6-f90f-11e6-913d-96addab2f3d4.png)

**Comment by anjesh** [comment]
This looks good to me, now we need to go through the wiki content and make further edits.
