### ISSUE TITLE
FAQ/Wiki

### ISSUE THREAD

**Issue by mireille-raad** [egovmd/opencontracting#15]
Section (something like FAQ) that explains in detail about the kind of data that is available within the portal. This can take the form of a wiki within the portal that can be updated by admin.

**Comment by mireille-raad** [comment]
I saw the current wiki hosted on github... i think it is a great place to host it, but do you think you can export/generate the wiki to a pdf or html format as well? I saw some scripts that do that, it might be handy to have it in 2 formats (on github and as web or pdf)

**Comment by anjesh** [comment]
Further discussion here https://github.com/younginnovations/opencontracting-moldova/issues/9
