### ISSUE TITLE
video tutorial 

### ISSUE THREAD

**Issue by mireille-raad** [egovmd/opencontracting#16]
A minimalist video tutorial (maybe screencast) that explains the portal and use of data within the portal.

**Comment by anjesh** [comment]
Here are some examples of video clips for review. They are not finalized yet. 
https://www.dropbox.com/sh/57d4ru29x455h7y/AACy0N7JJy98Xi3VKYfsHHCua?dl=0

**Comment by anjesh** [comment]
Further discussion here https://github.com/younginnovations/opencontracting-moldova/issues/10
