### ISSUE TITLE
allowing people to register for updates 

### ISSUE THREAD

**Issue by mireille-raad** [egovmd/opencontracting#17]
allowing people to register for updates

**Comment by mireille-raad** [comment]
So far, subscription is enabled, but the email newsletter title says "Moldova Newsletter" and needs to be changed to something more specific.

The newsletter mentions moldova@yipl as the contact reference for the list, this needs to be changed/updated as well.

Screenshots:

![moldovayipl](https://cloud.githubusercontent.com/assets/521705/22301664/cf704d3a-e2f9-11e6-8e9a-0f01e3838fe3.PNG)



![moldova newsletter](https://cloud.githubusercontent.com/assets/521705/22301614/a2e7277a-e2f9-11e6-9765-bd063fc27e01.PNG)

**Comment by mireille-raad** [comment]
On Windows 7, using chrome, I get the following display when trying to subscribe.

I am not sure if this is a "computer specific" problem, but it would be good to test on other windows/chrome

![already-subscribed](https://cloud.githubusercontent.com/assets/521705/22301745/1b9d1bac-e2fa-11e6-9473-368e54490574.PNG)

![thanks-for-subscribing](https://cloud.githubusercontent.com/assets/521705/22301751/1fcdb718-e2fa-11e6-9d6b-50dad6220a65.PNG)

**Comment by anjesh** [comment]
@bezunakarmi please have a look

**Comment by bezunakarmi** [comment]
This has been fixed. Please have a look.
![screen shot 2017-02-06 at 3 28 14 pm](https://cloud.githubusercontent.com/assets/12218329/22642001/095c3a96-ec81-11e6-91c0-e21302608750.png)
