### ISSUE TITLE
Periodic update with statistics.

### ISSUE THREAD

**Issue by mireille-raad** [egovmd/opencontracting#19]
System will automatically send periodic updates with statistics like latest contracts, top procuring agencies, etc. (will be based on visualizations developed within the portal) through push email notifications. The statistics will be generated automatically.

**Comment by anjesh** [comment]
This is how the the user will get the newsletters. All the reports are maintained in the mailchimp 
http://us14.campaign-archive1.com/?u=5be4e3c4761402dd284943876&id=8c7a334587

![image](https://cloud.githubusercontent.com/assets/120488/22421948/f862aac8-e711-11e6-9453-13cf5a017a4a.png)

cc @bezunakarmi

**Comment by mireille-raad** [comment]
1- Since this is a monthly newsletter, are these number about the past month (new data) or the summary of all the data on the portal? (I think it makes more sense if this about "last month in procurement" - we have to double check PPA for their thoughts on this)

2- Can this be made a little bit more visual?. A script can be scheduled to generate graphs/infographics  in a specific path on the server. Can this image/graph then be included in the newsletter? 

3- Do we have screenshots of how this would look like on mobile? I am assuming mail chimp takes care of it. But it is good to see it.

**Comment by anjesh** [comment]
To be discussed here if anything https://github.com/younginnovations/opencontracting-moldova/issues/11
