### ISSUE TITLE
Linkages to company details

### ISSUE THREAD

**Issue by mireille-raad** [egovmd/opencontracting#20]
Extract data on company details (available in date.gov.md) and link them to relevant section in the portal.

**Comment by mireille-raad** [comment]
Currently available on mouse hover. 
![company-info](https://cloud.githubusercontent.com/assets/521705/22303191/1de39a48-e300-11e6-84f8-908df255c18d.png)

But has problems on mobile and is hard to find in terms of UI.
Already agreed that it will be moved to a box, displayed regularly on the page.

**Comment by anjesh** [comment]
Updated. See http://moldova-demo.yipl.com.np/contracts/contractor/S.R.L.%20LUKOIL-Moldova#
![image](https://cloud.githubusercontent.com/assets/120488/22421849/6c474dd2-e711-11e6-9d3d-2c0801805c0f.png)
