### ISSUE TITLE
explore visualizing company linkages

### ISSUE THREAD

**Issue by mireille-raad** [egovmd/opencontracting#21]
explore if there is a possibility to visualize company linkages with each other and the contracts associated.

**Comment by anjesh** [comment]
I am working on the SNA analysis separately and then later we can go into the details on how we implement in portal, if we are to implement. I shall share it separately.

**Comment by mireille-raad** [comment]
let me know if you want to discuss the network graph visualization and how to implement beforehand... i've done a fair share of similar stuff and happy to brainstorm some easy to do stuff.

**Comment by anjesh** [comment]
Many thanks. I did quick R and here's what i came up with. Looking forward to your feedbacks. And definitely would love to hear about your experiences. 

I started with one company "NEGISTAN" and then searched for other companies related to the founders of this company and then people for those companies and on and on. There's so much linkages between companies and founders from the initial assessment, i tried following the graph in excel as well - the linkages are there. This graph is complex to present and and might go beyond the scope of work as well. The overhead is also high as the company names need to be cleaned up for proper matching, and there might be people sharing the same name, which would appear as one person in the analysis. Also there are lots of individual companies and name of that company is person itself. Also everytime new company excel is published, the process has to be continued and checked for inconsistencies. 

The graph below shows the linkages as we go deep

![image](https://cloud.githubusercontent.com/assets/120488/22689293/5f240eae-ed58-11e6-829a-9561c05ac8ad.png)

![image](https://cloud.githubusercontent.com/assets/120488/22688891/463a0a4e-ed56-11e6-948f-14cf3f5d4b94.png)

![image](https://cloud.githubusercontent.com/assets/120488/22688966/a904540e-ed56-11e6-8083-2123fff0d4db.png)

**Comment by mireille-raad** [comment]
Yeah - I think it would be too much to visualize company linkages...this becomes a "beneficiary ownership" project, not "open contracting".

I think it would be useful, or more manageable to have the following data set visualized:

Govt Agency (source) , Contractor (target), Value of all contracts (will be a property used to generate the size of the circle), nbre of contracts, Year (to maybe show network over time)

I think this will allow us to see who the govt agencies work with the most, if contractors work across agencies, if there are many small contracts or big ones etc. By filtering on one govt. agencies, you can see their network graph grow over the years or shrink.

It counts as visualizing the open contracting data in network graph format without having to do a lot of guess work.

does it sound more reasonable? if you think this is a good suggestion, can you share a csv with the exported dataset, i will tinker with it to see how the data would look like and if the network graphs are interesting.

Cheers!

**Comment by anjesh** [comment]
Further discussion here https://github.com/younginnovations/opencontracting-moldova/issues/13
