### ISSUE TITLE
Link data on court cases 

### ISSUE THREAD

**Issue by mireille-raad** [egovmd/opencontracting#22]
Link data on court cases which will be related to contractor's data available in the portal. The system will import data on court cases and link them to individual contractor pages if there are any court cases associated with them.

**Comment by mireille-raad** [comment]
Same as company info.

![court-case](https://cloud.githubusercontent.com/assets/521705/22303313/c06f3376-e300-11e6-88d3-56ab780a2324.png)

This doesn't work well on mobile and is hard to find for the user.

Already agreed that it will be displayed on the page in a regular box.

**Comment by anjesh** [comment]
Updated http://moldova-demo.yipl.com.np/contracts/contractor/S.R.L.%20LUKOIL-Moldova# 

![image](https://cloud.githubusercontent.com/assets/120488/22421828/48c8dde4-e711-11e6-9847-2a7780444b6a.png)
