### ISSUE TITLE
blacklisted contractors

### ISSUE THREAD

**Issue by mireille-raad** [egovmd/opencontracting#23]
Import data on blacklisting from etenders website and visualize them to associated contracts related to blacklisted ones.

**Comment by mireille-raad** [comment]
This is an example of a blacklisted contractor:
http://moldova-demo.yipl.com.np/contracts/contractor/DIVABONAS.R.L.

![blacklist](https://cloud.githubusercontent.com/assets/521705/22303393/1b56d410-e301-11e6-8e9c-57a8497a115f.PNG)

**Additional Question**
Is there a page where we can see a list of all blacklisted contractors? This can be added in the menu or in the homepage, after the contract list, we can add a box showing a link to black-listed contractors.
Another alternative is to add a graph to the homepage, showing blacklisted contractors over time.

**Comment by anjesh** [comment]
We have put the link to the tenders blacklisted contractor list 
http://moldova-demo.yipl.com.np/contracts/contractor/DIVABONAS.R.L.#

![image](https://cloud.githubusercontent.com/assets/120488/22451954/e396fbf6-e79a-11e6-8341-5b9ca4864837.png)

**Comment by mireille-raad** [comment]
:D i love the expendable "view court cases" option :)
