### ISSUE TITLE
displaying feedback / complaints received by PPA

### ISSUE THREAD

**Issue by mireille-raad** [egovmd/opencontracting#24]
explore the possibility of displaying feedback / complaints received by PPA with each individual contracts record in the portal.

**Comment by mireille-raad** [comment]
Example appeal information is displayed at the bottom of this page
http://moldova-demo.yipl.com.np/contracts/contractor/DIVABONAS.R.L.

![appeal](https://cloud.githubusercontent.com/assets/521705/22303580/e506200e-e301-11e6-8f27-1fa6266f2dd9.PNG)

**Comment by mireille-raad** [comment]
We agreed to put the link that takes to the PPA appeal listing. Place of link is to be determined

**Comment by bezunakarmi** [comment]
Appeals link is associated with tenders. This can be found in the tender's detail page. Please do have a look here : http://moldova-demo.yipl.com.np/tenders/9032986
![screen shot 2017-01-31 at 10 32 18 am](https://cloud.githubusercontent.com/assets/12218329/22452637/a1d1cff6-e7a0-11e6-96e2-b4ff798fdef9.png)
