### ISSUE TITLE
 authenticated discussion on individual contracts pages.

### ISSUE THREAD

**Issue by mireille-raad** [egovmd/opencontracting#25]
implement Discourse into the portal that will promote authenticated discussion on individual contracts pages.

**Comment by mireille-raad** [comment]
there is a new comment section for each contract now

![comments](https://cloud.githubusercontent.com/assets/521705/22303709/7133239c-e302-11e6-83fe-2b44644adb12.PNG)

**Question**
-  is there a comment moderation feature?
- The comments section is white, there is the "show more comments" button... once clicked, the comments show... can we show the first 5 or 3 comments and then have the button for more ?

**Comment by anjesh** [comment]
All the comments are shown now.

There's a basic moderation feature now - in which admin can see all the comments and quickly hide the comments. The comments are shown by default. 

![image](https://cloud.githubusercontent.com/assets/120488/22639524/88235392-ec76-11e6-8e5f-031bebe87679.png)

**Comment by mireille-raad** [comment]
I don't see this on the http://moldova-demo.yipl.com.np yet ;p - is this your local version?

![screen shot 2017-02-06 at 12 55 10 pm](https://cloud.githubusercontent.com/assets/521705/22659411/882cb6d6-ec6b-11e6-8cf6-d7fbc0c98aa4.png)

**Comment by mireille-raad** [comment]
I can now see the comments without having to click.
any links/login to see the comment moderation features?


<img width="1236" alt="screen shot 2017-02-10 at 2 22 48 pm" src="https://cloud.githubusercontent.com/assets/521705/22840686/87cb15b4-ef9c-11e6-9f34-7556337f34de.png">
