### ISSUE TITLE
Development of feature to visualize unit price information

### ISSUE THREAD

**Issue by mireille-raad** [egovmd/opencontracting#26]
Development of feature to visualize unit price information
This feature will provide a a way for the portal users to assess unit price information for goods and services procured as part of public procurement in Moldova. As far as possible, we will try to provide historic view of the unit price changes in the system in an interactive manner as well.

**Comment by mireille-raad** [comment]
-

**Comment by anjesh** [comment]
Will be looked into when we get the qty for items in award, which is present in the backend, not opened up yet.

**Comment by anjesh** [comment]
Further discussion here https://github.com/younginnovations/opencontracting-moldova/issues/17
