### ISSUE TITLE
include date of last refresh 

### ISSUE THREAD

**Issue by kaquino** [egovmd/opencontracting#27]
Include date of last data pull / refresh to: a) validate automatic pull of data is working; b) when it doesn't work, let users know when the data was last accurate.

**Comment by anjesh** [comment]
@bezunakarmi please have a look.

**Comment by bezunakarmi** [comment]
This has been done. Have a look.
![screen shot 2017-03-01 at 2 29 27 pm](https://cloud.githubusercontent.com/assets/12218329/23452204/968a22e0-fe8b-11e6-8e93-27a80dbb4058.png)
