### ISSUE TITLE
ErrorException in ContractsRepository.php - Undefined index: clearName

### ISSUE THREAD

**Issue by mireille-raad** [egovmd/opencontracting#28]
When clicking on a contractor
http://moldova-demo.yipl.com.np/contracts/contractor/COMPANIA%20ELECTRICĂ%20S.A.
![screen shot 2017-02-06 at 12 38 23 pm](https://cloud.githubusercontent.com/assets/521705/22658750/2f627d3a-ec69-11e6-9af4-8d727d5dffe8.png)

**Comment by anjesh** [comment]
can you check if this is still the case? [link](http://moldova-demo.yipl.com.np/contracts/contractor/COMPANIA%20ELECTRIC%C4%82%20S.A.) is working now

**Comment by mireille-raad** [comment]
yap, working
