### ISSUE TITLE
Moldova newsletter text

### ISSUE THREAD

**Issue by mireille-raad** [egovmd/opencontracting#29]
Hey :)

for the newsletter, it says "Moldova Newsletter" and the email mentioned there is for YI.

![moldovaemail](https://cloud.githubusercontent.com/assets/521705/22936094/74443530-f2a2-11e6-9080-2d4ba4d1c14f.PNG)

Can we update the title to include something like Moldova Open Contracting Newsletter (or what you see fit)

Also, let me know if you need me to figure out what email to put there instead of moldova@yipl.com.

**Comment by anjesh** [comment]
Thanks @dc-coder. We will use this email address data@opencontracting.etenders.gov.md mentioned in the about page http://moldova-demo.yipl.com.np/about

**Comment by anjesh** [comment]
cc @bezunakarmi

**Comment by bezunakarmi** [comment]
I have changed the email to  office@egov.md as specified in the email. Also have send a verification email. Please do check.

**Comment by mireille-raad** [comment]
I ran out of emails to test... sorry to waste your time with this... but can you remove/unsubscribe me from newsletter? all the mireilleraad, mir.mir, mraad emails are mine. Once removed, i will retest.

Alternatively you can share a screenshot, just to make sure all looks ok before closing this.

cheers!

**Comment by bezunakarmi** [comment]
I have deleted all the subscribed/unsubscribed email from mailchimp. And the email also has been changed.
![screen shot 2017-03-01 at 10 45 39 am](https://cloud.githubusercontent.com/assets/12218329/23446526/608191b6-fe6c-11e6-9657-4e7874b1be0a.png)

**Comment by anjesh** [comment]
If anything, to be discussed here https://github.com/younginnovations/opencontracting-moldova/issues/11
