### ISSUE TITLE
Items are not captured for awards or contracts

### ISSUE THREAD

**Issue by mireille-raad** [egovmd/opencontracting#3]
Items are not captured for awards or contracts, if this information is available in the source systems in Moldova then exposing it would help track items to contracts where multiple awards result from a singe tender process

**Comment by anjesh** [comment]
Items are captured for awards see http://moldova-demo.yipl.com.np/contracts/183943

![image](https://cloud.githubusercontent.com/assets/120488/22452027/69a3cdbe-e79b-11e6-9d6f-67ebec9405e4.png)

As per data, there's one award associated with the one contract only, as there's no separate award json in etenders, but rather we pulled award information from etenders contracts json. Also when items are present in awards, there's no need to mention items in contracts as per OCDS. There's awardID associated with the contract block in OCDS.
