### ISSUE TITLE
releases-year.json does not validate on http://standard.open-contracting.org/validator/

### ISSUE THREAD

**Issue by mireille-raad** [egovmd/opencontracting#30]
when i try to validate the OCDS data at http://standard.open-contracting.org/validator/, I get the following error.

![ocds-validaor](https://cloud.githubusercontent.com/assets/521705/22936407/6bd3f34e-f2a3-11e6-8c1f-fb0169d2ff53.PNG)

**Comment by bezunakarmi** [comment]
We have made changes to the JSON file, checked it through the OCDS validator and now we have validation error for status/text written in Romanian language.
![screen shot 2017-02-20 at 4 41 07 pm](https://cloud.githubusercontent.com/assets/12218329/23122284/b794e72e-f78b-11e6-9db6-d5b04fbf7f86.png)

**Comment by mireille-raad** [comment]
After checking a few releases in the validator, i think the main validation errors are:

1. Published date missing but required
2. Releases missing but required
3. uri missing but required
4. codelist in romanian
5. some values are negative while validator says should be > 0 (I am not sure if there has been a change in OCDS for that)

<img width="1172" alt="screen shot 2017-02-20 at 11 11 51 am" src="https://cloud.githubusercontent.com/assets/521705/23133126/079c0ac8-f75e-11e6-8dd8-dba04a9b7300.png">

Link to 2017 release validation
http://standard.open-contracting.org/validator/data/1a0e0680-1508-4993-9d08-a4d43e81a502 

Link to 2015 release validation
http://standard.open-contracting.org/validator/data/e56ebd9c-8513-4923-b0fb-b2f9c1c49bb4

So, @anjesh , do you think we can fix the first 3 validation errors and can you get in touch with Open Data Services Help Desk for guidance on the others errors? ( I am happy to do it, but I think it is better if you have direct conversation with them)

**Comment by bezunakarmi** [comment]
Following validation error has been fixed:

1. Publshed Date has been added.
2. Releases error has been resolved.
3. Missing URI has been added.

Link to 2017 release validation
http://standard.open-contracting.org/validator/data/46835a6c-12d6-472e-9283-e92913ddb6b9

Link to 2015 release validation
http://standard.open-contracting.org/validator/data/f6229ed9-d85b-45b6-a929-aedd7ea87049

**Comment by mireille-raad** [comment]
excellent!!! thanks!!
