### ISSUE TITLE
Option to download bulk JSON data 

### ISSUE THREAD

**Issue by mireille-raad** [egovmd/opencontracting#4]
Option to download bulk JSON data on the portal could be a useful feature for future iterations.

**Comment by bezunakarmi** [comment]
We have worked on downloading bulk JSON data from the portal. Generating a single JSON file for all the data will take a huge amount of resources as well as the size of the JSON file will be large. So, for now we have create separate JSON files of contract data according to the issue date of tenders. We will provide a JSON file which will contain all the links to the particular JSON files order by tender issue date. The "Download JSON" link can be found just above the footer bar in the site or you can click on this link
http://moldova-demo.yipl.com.np/multiple-file-api/releases.json
![screen shot 2017-02-02 at 4 56 05 pm](https://cloud.githubusercontent.com/assets/12218329/22547362/646090a6-e969-11e6-9b77-61c8bc27bba0.png)
![screen shot 2017-02-02 at 5 02 01 pm](https://cloud.githubusercontent.com/assets/12218329/22547367/6b63d584-e969-11e6-9320-e8a117d22046.png)

**Comment by mireille-raad** [comment]
When I download, i get the following:

![releases-json](https://cloud.githubusercontent.com/assets/521705/22936260/f193ce24-f2a2-11e6-97bb-107d0b9470a8.PNG)

can the localhost be replaced? cuz for people this might be a little bit confusing, since the links won't resolve.

**Comment by bezunakarmi** [comment]
We have resolved this issue. Please have a look [here](http://moldova-demo.yipl.com.np/multiple-file-api/releases.json)

**Comment by mireille-raad** [comment]
hmm just re-tried it... still shows the same localhost

```json{
  "links": {
    "all": [
      "http://localhost:8000/ocds-api/year/2017",
      "http://localhost:8000/ocds-api/year/2016",
      "http://localhost:8000/ocds-api/year/2015",
      "http://localhost:8000/ocds-api/year/2014",
      "http://localhost:8000/ocds-api/year/2013",
      "http://localhost:8000/ocds-api/year/2012"
    ]
  }
}```

tried the direct link you gave and going to http://moldova-demo.yipl.com.np/ then downloading.

**Comment by mireille-raad** [comment]
Ooops, worked... had to disable cache a few times :) :+1:
