### ISSUE TITLE
responsive issues when language is switched.

### ISSUE THREAD

**Issue by mireille-raad** [egovmd/opencontracting#8]
Correct some responsive issues when language is changed from english to romanian or vice versa

![menu](https://cloud.githubusercontent.com/assets/521705/22301085/ac31154a-e2f7-11e6-9354-c19d298e1536.png)

**Comment by bezunakarmi** [comment]
This issue was not visible in Mac browsers, so we checked in different browsers of linux and windows. We have fixed this issue. Please do have a look.
![screen shot 2017-01-31 at 10 23 11 am](https://cloud.githubusercontent.com/assets/12218329/22452507/984c5fd8-e79f-11e6-8a87-6a4ff4e03a61.png)

**Comment by anjesh** [comment]
Please reopen if you still have this issue.
