### ISSUE TITLE
Setup server

### ISSUE THREAD

**Issue by mireille-raad** [egovmd/opencontracting#9]
Work with eGC to setup server to host the portal. Specifically, we need the server to run necessary services to enable the portal operation.

**Comment by mireille-raad** [comment]
are you set for this task? do we need to provide you with any further information? should we follow-up on server details/login with anyone?

**Comment by anjesh** [comment]
hi @dc-coder we have received info from EGC and infact http://moldova-demo.yipl.com.np/ is already hosted in their server. We need to update A record for opencontracting.date.gov.md to this new server if we are happy with the changes in demo site so far.

**Comment by mireille-raad** [comment]
Excellent! glad you have all details you need :)))

**Comment by anjesh** [comment]
Server info all received. Need to point A record only. New issue to be created for that in https://github.com/younginnovations/opencontracting-moldova/issues
